services:
  - type: web
    name: disease-portal
    runtime: python
    buildCommand: pip install -r requirements.txt && python download_db.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
